apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtehbhy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtehbhy
  template:
    metadata:
      labels:
        app: rtehbhy
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: rtehbhy
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "98f4e10c-6541-4f7a-ac42-97a6ef52278d"
        - name: Vless_Path
          value: "/vl555yty"
        - name: Vmess_UUID
          value: "98f4e10c-6541-4f7a-ac42-97a6ef52278d"
        - name: Vmess_Path
          value: "/vm666fhhf"
        - name: Share_Path
          value: "/v2link"
